<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TumbuhanSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        DB::table('tmst_tumbuhan')->insert([
            // Data KE 1
            [
                'nama_tumbuhan' => 'ADAS, ADAS JAMU (FENNEL)',
                'nama_latin' => 'Foeniculum vulgare Mill',
                'sinonim' => 'Anethum dulce DC.|Foeniculum giganteum Lojac.|Anethum foeniculum L.|Foeniculum officinale All.|Anethum minus Gouan|Foeniculum panmorium (Roxb.) DC.|Anethum panmori Roxb.|Foeniculum piperitum C. Presl|Anethum panmorium Roxb. ex Fleming|Foeniculum rigidum Brot. ex Steud.|Anethum pannorium Roxb.|Ligusticum foeniculum (L.) Crantz|Anethum rupestre Salisb.|Ligusticum foeniculum (L.) Roth|Foeniculum azoricum Mill.|Meum foeniculum (L.y) Spreng.|Foeniculum divaricatum Griseb.|Selinum foeniculum E. H. L. Krause|Foeniculum dulce Mill.|Seseli foeniculum Koso-Pol.',
                'nama_daerah' => 'Adas manis, jintan manis',
                'kerajaan' => 'Plantae (Tumbuhan)',
                'sub_kerajaan' => 'Tracheobionta (Tumbuhan berpembuluh)',
                'super_divisi' => 'Spermatophyta (Tumbuhan berbiji)',
                'divisi' => 'Magnoliophyta (Tumbuhan berbunga)',
                'kelas' => 'Magnoliopsida (Berkeping dua/ Dikotil)',
                'sub_kelas' => 'Rosidae',
                'ordo' => 'Apiales',
                'famili' => 'Apiaceae',
                'genus' => 'Pimpinella',
                'spesies' => 'Pimpinella anisum L.',
                'deskripsi' => 'Terna setahun, tinggi 10 - 45 cm. Batang beruas-ruas sempit. Daun menyirip ganda. Bunga memiliki mahkota yang mirip dengan kelopak. Buah berupa kapsul bulat, licin. Biji bersudut tiga, beriga melintang. Jintan manis merupakan jenis tumbuhan yang belum banyak dibudidayakan oleh masyarakat Indonesia.',
                'bagian_yg_digunakan' => 'Minyak esensial yang berasal dari buah yang matang dan buah yang kering.',
                'konstituen' => 'Minyak esensial: Alfa pinen, alfa-terpinen, anetol, anisaldehida, asam-anisat. Buah: Asetaldehida, asam-anisat, bergapten, dianetol, estragol. Daun: Alfa-tokoferol, imperatorin, isokuersitrin, skoparon, skopoletin, seselin. Tanaman: Alfa-zingiberen, anetol, beta-amirin, beta-bisabolen, asam-kafeat. Akar: Alfa-tokoferol, anetol, isopimpinelin, manitol. Biji: Anetol, dianetol, estragol, eugenol, umbeliferon. Minyak esensial biji: Beta-elemen, kamfor, karvon, sinamaldehida, sinamal-alkohol. Tunas: Anetol. Kultur jaringan: Alfa-tokoferol, anetol, beta-bisabolen, beta-sitosterol, miristisin.',
                'indikasi' => 'Andropause, Anemia, Anoreksia, Asma Bakteria, Batuk rejan (Pertusis), Batuk, Bau mulut, Demam, Nyeri haid, Dispepsia, Dropsi, Epilepsi, Frigiditas, Gugup, Indurasi, Infeksi, Kanker ginjal, Kanker hati, Kanker kandung kemih, Kanker lambung, Kanker limpa, Kanker paru, Kanker rahim, Kanker uvula, Kanker, Kolera, Kolesistosis, Kolik, Kolitis, Kongesti, Konvulsi, Kram, Kudis (dioles), Kutu rambut (dioles), Kutu rambut, Mempermudah persalinan, Infeksi jamur, Mual (hamil muda), Mual, Mukosis, Neuralgia, Nyeri, Parasit, Pasokan susu yang buruk, Penyakit bronkus paru, Penyakit ginjal, Penyakit hati, Penyakit jamur, Penyakit lambung, Penyakit limpa, Penyakit pernafasan, Penyakit rongga mulut, Penyakit sendi, Penyakit tenggorokan, Psorias, Radang selaput lendir hidung dan tenggorokan, Sakit kepala sebelah, Sakit pinggang, Selesma, Sendawa/ Perut kembung, Sklerosis, Susah tidur, Terapi pengganti estrogen, Trakeosis, Tuber kulosis, Tumor, Ulkus (Borok), Virus.',
                'penggunaan_tradisional' => 'Adas manis (Pimpinella anisum) merupakan rempah-rempah dengan rasa manis pada bijinya, sangat baik untuk menghilangkan lendir di dalam tubuh, mengatasi kram perut, kolik dan perut kembung. Adas Manis sangat baik digunakan sebagai penenang sistim saraf dan mengatasi masalah sulit tidur. Adas manis merupakan bahan baku obat antivirus yang dapat menangani virus flu burung, ekstrak adas manis atau kembang lawang ini diekspor ke Korea yang selanjutnya dibuat antivirus flu burung yang bernama "Tamiflu". Adas manis digunakan sebagai rempah-rempah dalam memberikan rasa pada kari, permen, kue dan minuman. Daunnya juga digunakan dalam memberikan rasa pada berbagai permen. Buahnya dapat menghasilkan minyak atsiri yang dapat dipakai sebagai pengganti buahnya. Minyak adas manis dapat juga digunakan sebagai bahan untuk parfum, sabun dan insektisida. Buah adas manis juga digunakan sebagai tonik untuk ibu-ibu setelah melahirkan.',
                'dosis_harian' => '1 sendok teh biji dilembutkan/ cangkir air 3×/ hari, 3 g biji, atau 300 mg minyak biji/ hari 0,5 - 1 g biji sebagai minuman teh, 3×/ hari 0,5 - 3 g buah, 20 g buah dalam air, 0,5 - 1 sendok teh sirup hingga 3×/ hari, Minyak esensial 0,05 - 0,2 ml buah, 0,3 - 1 ml air adas manis. Atau, penggunaan internal: Dosis harian rata-rata 3 g. Minum 1 cangkir teh di pagi atau sore hari sebagai ekspektoran. 2 sendok makan untuk mengatasi keluhan lambung. Untuk bayi, dapat menggunakan seduhan 1 sendok teh yang ditambahkan pada botol minumannya. Penggunaan eksternal: Minyak esensialnya dapat digunakan dengan cara dihirup.',
                'kontra_indikasi' => 'Tidak ada bahaya Kesehatan atau efek samping yang dikenal dengan pemberian dosis terapi yang tepat. Dikontraindikasikan pada pasien alergi, namun sangat jarang terjadi. Reaksi alergi sesekali pada kulit, saluran pernapasan dan saluran pencernaan. Minyak esensial adas manis memiliki efek anti bakteri, antivirus, ekspektoran, estrogenik, karminatif, pengusir nyamuk dan spasmolitik ringan. 1 - 5 ml dapat menyebabkan mual, edema paru, kejang, dan muntah. Minyak Esensial LD50= 2.700 mg/ kg ORL tikus. Kontraindikasi untuk buah: hipersensitivitas. Efek samping: terkadang terdapat reaksi alergi. Biji, dilaporkan bersifat abortifasien dan laktagoga, sebaiknya tidak digunakan pada kehamilan. "Sering digunakan dalam praktek pediatrik". Ibu menyusui mengkonsumsi adas manis atau teh adas, atau keduanya, untuk merangsang laktasi. Dosis berlebihan dapat mengganggu antikoagulan, kontrasepsi, terapi pengganti estrogen, dan terapi penghambat Monoamin Oksidase (Monoamine Oxidase Inhibitor, MAOI). Adas manis berpotensi seperti efek estrogen.',
                'dapus' => '',
                'sumber_internet' => '',
                'gambar' => ''
            ],
            // Data KE 2
            [
                'nama_tumbuhan' => 'ADAS MANIS (ANISE)',
                'nama_latin' => 'Pimpinella anisum L.',
                'sinonim' => 'Anethum dulce DC.|Foeniculum giganteum Lojac.|Anethum foeniculum L.|Foeniculum officinale All.|Anethum minus Gouan|Foeniculum panmorium (Roxb.) DC.|Anethum panmori Roxb.|Foeniculum piperitum C. Presl|Anethum panmorium Roxb. ex Fleming|Foeniculum rigidum Brot. ex Steud.|Anethum pannorium Roxb.|Ligusticum foeniculum (L.) Crantz|Anethum rupestre Salisb.|Ligusticum foeniculum (L.) Roth|Foeniculum azoricum Mill.|Meum foeniculum (L.y) Spreng.|Foeniculum divaricatum Griseb.|Selinum foeniculum E. H. L. Krause|Foeniculum dulce Mill.|Seseli foeniculum Koso-Pol.',
                'nama_daerah' => 'Adas manis, jintan manis',
                'kerajaan' => 'Plantae (Tumbuhan)',
                'sub_kerajaan' => 'Tracheobionta (Tumbuhan berpembuluh)',
                'super_divisi' => 'Spermatophyta (Tumbuhan berbiji)',
                'divisi' => 'Magnoliophyta (Tumbuhan berbunga)',
                'kelas' => 'Magnoliopsida (Berkeping dua/ Dikotil)',
                'sub_kelas' => 'Rosidae',
                'ordo' => 'Apiales',
                'famili' => 'Apiaceae',
                'genus' => 'Pimpinella',
                'spesies' => 'Pimpinella anisum L.',
                'deskripsi' => 'Terna setahun, tinggi 10 - 45 cm. Batang beruas-ruas sempit. Daun menyirip ganda. Bunga memiliki mahkota yang mirip dengan kelopak. Buah berupa kapsul bulat, licin. Biji bersudut tiga, beriga melintang. Jintan manis merupakan jenis tumbuhan yang belum banyak dibudidayakan oleh masyarakat Indonesia.',
                'bagian_yg_digunakan' => 'Minyak esensial yang berasal dari buah yang matang dan buah yang kering.',
                'konstituen' => 'Minyak esensial: Alfa pinen, alfa-terpinen, anetol, anisaldehida, asam-anisat. Buah: Asetaldehida, asam-anisat, bergapten, dianetol, estragol. Daun: Alfa-tokoferol, imperatorin, isokuersitrin, skoparon, skopoletin, seselin. Tanaman: Alfa-zingiberen, anetol, beta-amirin, beta-bisabolen, asam-kafeat. Akar: Alfa-tokoferol, anetol, isopimpinelin, manitol. Biji: Anetol, dianetol, estragol, eugenol, umbeliferon. Minyak esensial biji: Beta-elemen, kamfor, karvon, sinamaldehida, sinamal-alkohol. Tunas: Anetol. Kultur jaringan: Alfa-tokoferol, anetol, beta-bisabolen, beta-sitosterol, miristisin.',
                'indikasi' => 'Andropause, Anemia, Anoreksia, Asma Bakteria, Batuk rejan (Pertusis), Batuk, Bau mulut, Demam, Nyeri haid, Dispepsia, Dropsi, Epilepsi, Frigiditas, Gugup, Indurasi, Infeksi, Kanker ginjal, Kanker hati, Kanker kandung kemih, Kanker lambung, Kanker limpa, Kanker paru, Kanker rahim, Kanker uvula, Kanker, Kolera, Kolesistosis, Kolik, Kolitis, Kongesti, Konvulsi, Kram, Kudis (dioles), Kutu rambut (dioles), Kutu rambut, Mempermudah persalinan, Infeksi jamur, Mual (hamil muda), Mual, Mukosis, Neuralgia, Nyeri, Parasit, Pasokan susu yang buruk, Penyakit bronkus paru, Penyakit ginjal, Penyakit hati, Penyakit jamur, Penyakit lambung, Penyakit limpa, Penyakit pernafasan, Penyakit rongga mulut, Penyakit sendi, Penyakit tenggorokan, Psorias, Radang selaput lendir hidung dan tenggorokan, Sakit kepala sebelah, Sakit pinggang, Selesma, Sendawa/ Perut kembung, Sklerosis, Susah tidur, Terapi pengganti estrogen, Trakeosis, Tuber kulosis, Tumor, Ulkus (Borok), Virus.',
                'penggunaan_tradisional' => 'Adas manis (Pimpinella anisum) merupakan rempah-rempah dengan rasa manis pada bijinya, sangat baik untuk menghilangkan lendir di dalam tubuh, mengatasi kram perut, kolik dan perut kembung. Adas Manis sangat baik digunakan sebagai penenang sistim saraf dan mengatasi masalah sulit tidur. Adas manis merupakan bahan baku obat antivirus yang dapat menangani virus flu burung, ekstrak adas manis atau kembang lawang ini diekspor ke Korea yang selanjutnya dibuat antivirus flu burung yang bernama "Tamiflu". Adas manis digunakan sebagai rempah-rempah dalam memberikan rasa pada kari, permen, kue dan minuman. Daunnya juga digunakan dalam memberikan rasa pada berbagai permen. Buahnya dapat menghasilkan minyak atsiri yang dapat dipakai sebagai pengganti buahnya. Minyak adas manis dapat juga digunakan sebagai bahan untuk parfum, sabun dan insektisida. Buah adas manis juga digunakan sebagai tonik untuk ibu-ibu setelah melahirkan.',
                'dosis_harian' => '1 sendok teh biji dilembutkan/ cangkir air 3×/ hari, 3 g biji, atau 300 mg minyak biji/ hari 0,5 - 1 g biji sebagai minuman teh, 3×/ hari 0,5 - 3 g buah, 20 g buah dalam air, 0,5 - 1 sendok teh sirup hingga 3×/ hari, Minyak esensial 0,05 - 0,2 ml buah, 0,3 - 1 ml air adas manis. Atau, penggunaan internal: Dosis harian rata-rata 3 g. Minum 1 cangkir teh di pagi atau sore hari sebagai ekspektoran. 2 sendok makan untuk mengatasi keluhan lambung. Untuk bayi, dapat menggunakan seduhan 1 sendok teh yang ditambahkan pada botol minumannya. Penggunaan eksternal: Minyak esensialnya dapat digunakan dengan cara dihirup.',
                'kontra_indikasi' => 'Tidak ada bahaya Kesehatan atau efek samping yang dikenal dengan pemberian dosis terapi yang tepat. Dikontraindikasikan pada pasien alergi, namun sangat jarang terjadi. Reaksi alergi sesekali pada kulit, saluran pernapasan dan saluran pencernaan. Minyak esensial adas manis memiliki efek anti bakteri, antivirus, ekspektoran, estrogenik, karminatif, pengusir nyamuk dan spasmolitik ringan. 1 - 5 ml dapat menyebabkan mual, edema paru, kejang, dan muntah. Minyak Esensial LD50= 2.700 mg/ kg ORL tikus. Kontraindikasi untuk buah: hipersensitivitas. Efek samping: terkadang terdapat reaksi alergi. Biji, dilaporkan bersifat abortifasien dan laktagoga, sebaiknya tidak digunakan pada kehamilan. "Sering digunakan dalam praktek pediatrik". Ibu menyusui mengkonsumsi adas manis atau teh adas, atau keduanya, untuk merangsang laktasi. Dosis berlebihan dapat mengganggu antikoagulan, kontrasepsi, terapi pengganti estrogen, dan terapi penghambat Monoamin Oksidase (Monoamine Oxidase Inhibitor, MAOI). Adas manis berpotensi seperti efek estrogen.',
                'dapus' => '',
                'sumber_internet' => '',
                'gambar' => ''
            ],
            // Data KE 3
            [
                'nama_tumbuhan' => 'ADAS SOWA (DILL)',
                'nama_latin' => 'Anethum graveolens L.',
                'sinonim' => 'Anethum dulce DC.|Foeniculum giganteum Lojac.|Anethum foeniculum L.|Foeniculum officinale All.|Anethum minus Gouan|Foeniculum panmorium (Roxb.) DC.|Anethum panmori Roxb.|Foeniculum piperitum C. Presl|Anethum panmorium Roxb. ex Fleming|Foeniculum rigidum Brot. ex Steud.|Anethum pannorium Roxb.|Ligusticum foeniculum (L.) Crantz|Anethum rupestre Salisb.|Ligusticum foeniculum (L.) Roth|Foeniculum azoricum Mill.|Meum foeniculum (L.y) Spreng.|Foeniculum divaricatum Griseb.|Selinum foeniculum E. H. L. Krause|Foeniculum dulce Mill.|Seseli foeniculum Koso-Pol.',
                'nama_daerah' => 'Adas manis, jintan manis',
                'kerajaan' => 'Plantae (Tumbuhan)',
                'sub_kerajaan' => 'Tracheobionta (Tumbuhan berpembuluh)',
                'super_divisi' => 'Spermatophyta (Tumbuhan berbiji)',
                'divisi' => 'Magnoliophyta (Tumbuhan berbunga)',
                'kelas' => 'Magnoliopsida (Berkeping dua/ Dikotil)',
                'sub_kelas' => 'Rosidae',
                'ordo' => 'Apiales',
                'famili' => 'Apiaceae',
                'genus' => 'Pimpinella',
                'spesies' => 'Pimpinella anisum L.',
                'deskripsi' => 'Terna setahun, tinggi 10 - 45 cm. Batang beruas-ruas sempit. Daun menyirip ganda. Bunga memiliki mahkota yang mirip dengan kelopak. Buah berupa kapsul bulat, licin. Biji bersudut tiga, beriga melintang. Jintan manis merupakan jenis tumbuhan yang belum banyak dibudidayakan oleh masyarakat Indonesia.',
                'bagian_yg_digunakan' => 'Minyak esensial yang berasal dari buah yang matang dan buah yang kering.',
                'konstituen' => 'Minyak esensial: Alfa pinen, alfa-terpinen, anetol, anisaldehida, asam-anisat. Buah: Asetaldehida, asam-anisat, bergapten, dianetol, estragol. Daun: Alfa-tokoferol, imperatorin, isokuersitrin, skoparon, skopoletin, seselin. Tanaman: Alfa-zingiberen, anetol, beta-amirin, beta-bisabolen, asam-kafeat. Akar: Alfa-tokoferol, anetol, isopimpinelin, manitol. Biji: Anetol, dianetol, estragol, eugenol, umbeliferon. Minyak esensial biji: Beta-elemen, kamfor, karvon, sinamaldehida, sinamal-alkohol. Tunas: Anetol. Kultur jaringan: Alfa-tokoferol, anetol, beta-bisabolen, beta-sitosterol, miristisin.',
                'indikasi' => 'Andropause, Anemia, Anoreksia, Asma Bakteria, Batuk rejan (Pertusis), Batuk, Bau mulut, Demam, Nyeri haid, Dispepsia, Dropsi, Epilepsi, Frigiditas, Gugup, Indurasi, Infeksi, Kanker ginjal, Kanker hati, Kanker kandung kemih, Kanker lambung, Kanker limpa, Kanker paru, Kanker rahim, Kanker uvula, Kanker, Kolera, Kolesistosis, Kolik, Kolitis, Kongesti, Konvulsi, Kram, Kudis (dioles), Kutu rambut (dioles), Kutu rambut, Mempermudah persalinan, Infeksi jamur, Mual (hamil muda), Mual, Mukosis, Neuralgia, Nyeri, Parasit, Pasokan susu yang buruk, Penyakit bronkus paru, Penyakit ginjal, Penyakit hati, Penyakit jamur, Penyakit lambung, Penyakit limpa, Penyakit pernafasan, Penyakit rongga mulut, Penyakit sendi, Penyakit tenggorokan, Psorias, Radang selaput lendir hidung dan tenggorokan, Sakit kepala sebelah, Sakit pinggang, Selesma, Sendawa/ Perut kembung, Sklerosis, Susah tidur, Terapi pengganti estrogen, Trakeosis, Tuber kulosis, Tumor, Ulkus (Borok), Virus.',
                'penggunaan_tradisional' => 'Adas manis (Pimpinella anisum) merupakan rempah-rempah dengan rasa manis pada bijinya, sangat baik untuk menghilangkan lendir di dalam tubuh, mengatasi kram perut, kolik dan perut kembung. Adas Manis sangat baik digunakan sebagai penenang sistim saraf dan mengatasi masalah sulit tidur. Adas manis merupakan bahan baku obat antivirus yang dapat menangani virus flu burung, ekstrak adas manis atau kembang lawang ini diekspor ke Korea yang selanjutnya dibuat antivirus flu burung yang bernama "Tamiflu". Adas manis digunakan sebagai rempah-rempah dalam memberikan rasa pada kari, permen, kue dan minuman. Daunnya juga digunakan dalam memberikan rasa pada berbagai permen. Buahnya dapat menghasilkan minyak atsiri yang dapat dipakai sebagai pengganti buahnya. Minyak adas manis dapat juga digunakan sebagai bahan untuk parfum, sabun dan insektisida. Buah adas manis juga digunakan sebagai tonik untuk ibu-ibu setelah melahirkan.',
                'dosis_harian' => '1 sendok teh biji dilembutkan/ cangkir air 3×/ hari, 3 g biji, atau 300 mg minyak biji/ hari 0,5 - 1 g biji sebagai minuman teh, 3×/ hari 0,5 - 3 g buah, 20 g buah dalam air, 0,5 - 1 sendok teh sirup hingga 3×/ hari, Minyak esensial 0,05 - 0,2 ml buah, 0,3 - 1 ml air adas manis. Atau, penggunaan internal: Dosis harian rata-rata 3 g. Minum 1 cangkir teh di pagi atau sore hari sebagai ekspektoran. 2 sendok makan untuk mengatasi keluhan lambung. Untuk bayi, dapat menggunakan seduhan 1 sendok teh yang ditambahkan pada botol minumannya. Penggunaan eksternal: Minyak esensialnya dapat digunakan dengan cara dihirup.',
                'kontra_indikasi' => 'Tidak ada bahaya Kesehatan atau efek samping yang dikenal dengan pemberian dosis terapi yang tepat. Dikontraindikasikan pada pasien alergi, namun sangat jarang terjadi. Reaksi alergi sesekali pada kulit, saluran pernapasan dan saluran pencernaan. Minyak esensial adas manis memiliki efek anti bakteri, antivirus, ekspektoran, estrogenik, karminatif, pengusir nyamuk dan spasmolitik ringan. 1 - 5 ml dapat menyebabkan mual, edema paru, kejang, dan muntah. Minyak Esensial LD50= 2.700 mg/ kg ORL tikus. Kontraindikasi untuk buah: hipersensitivitas. Efek samping: terkadang terdapat reaksi alergi. Biji, dilaporkan bersifat abortifasien dan laktagoga, sebaiknya tidak digunakan pada kehamilan. "Sering digunakan dalam praktek pediatrik". Ibu menyusui mengkonsumsi adas manis atau teh adas, atau keduanya, untuk merangsang laktasi. Dosis berlebihan dapat mengganggu antikoagulan, kontrasepsi, terapi pengganti estrogen, dan terapi penghambat Monoamin Oksidase (Monoamine Oxidase Inhibitor, MAOI). Adas manis berpotensi seperti efek estrogen.',
                'dapus' => '',
                'sumber_internet' => '',
                'gambar' => ''
            ],
            // Data KE 4
            [
                'nama_tumbuhan' => 'AJERAN, KETUL (SPANISH NEEDLES)',
                'nama_latin' => 'Bidens pilosa L',
                'sinonim' => 'Anethum dulce DC.|Foeniculum giganteum Lojac.|Anethum foeniculum L.|Foeniculum officinale All.|Anethum minus Gouan|Foeniculum panmorium (Roxb.) DC.|Anethum panmori Roxb.|Foeniculum piperitum C. Presl|Anethum panmorium Roxb. ex Fleming|Foeniculum rigidum Brot. ex Steud.|Anethum pannorium Roxb.|Ligusticum foeniculum (L.) Crantz|Anethum rupestre Salisb.|Ligusticum foeniculum (L.) Roth|Foeniculum azoricum Mill.|Meum foeniculum (L.y) Spreng.|Foeniculum divaricatum Griseb.|Selinum foeniculum E. H. L. Krause|Foeniculum dulce Mill.|Seseli foeniculum Koso-Pol.',
                'nama_daerah' => 'Adas manis, jintan manis',
                'kerajaan' => 'Plantae (Tumbuhan)',
                'sub_kerajaan' => 'Tracheobionta (Tumbuhan berpembuluh)',
                'super_divisi' => 'Spermatophyta (Tumbuhan berbiji)',
                'divisi' => 'Magnoliophyta (Tumbuhan berbunga)',
                'kelas' => 'Magnoliopsida (Berkeping dua/ Dikotil)',
                'sub_kelas' => 'Rosidae',
                'ordo' => 'Apiales',
                'famili' => 'Apiaceae',
                'genus' => 'Pimpinella',
                'spesies' => 'Pimpinella anisum L.',
                'deskripsi' => 'Terna setahun, tinggi 10 - 45 cm. Batang beruas-ruas sempit. Daun menyirip ganda. Bunga memiliki mahkota yang mirip dengan kelopak. Buah berupa kapsul bulat, licin. Biji bersudut tiga, beriga melintang. Jintan manis merupakan jenis tumbuhan yang belum banyak dibudidayakan oleh masyarakat Indonesia.',
                'bagian_yg_digunakan' => 'Minyak esensial yang berasal dari buah yang matang dan buah yang kering.',
                'konstituen' => 'Minyak esensial: Alfa pinen, alfa-terpinen, anetol, anisaldehida, asam-anisat. Buah: Asetaldehida, asam-anisat, bergapten, dianetol, estragol. Daun: Alfa-tokoferol, imperatorin, isokuersitrin, skoparon, skopoletin, seselin. Tanaman: Alfa-zingiberen, anetol, beta-amirin, beta-bisabolen, asam-kafeat. Akar: Alfa-tokoferol, anetol, isopimpinelin, manitol. Biji: Anetol, dianetol, estragol, eugenol, umbeliferon. Minyak esensial biji: Beta-elemen, kamfor, karvon, sinamaldehida, sinamal-alkohol. Tunas: Anetol. Kultur jaringan: Alfa-tokoferol, anetol, beta-bisabolen, beta-sitosterol, miristisin.',
                'indikasi' => 'Andropause, Anemia, Anoreksia, Asma Bakteria, Batuk rejan (Pertusis), Batuk, Bau mulut, Demam, Nyeri haid, Dispepsia, Dropsi, Epilepsi, Frigiditas, Gugup, Indurasi, Infeksi, Kanker ginjal, Kanker hati, Kanker kandung kemih, Kanker lambung, Kanker limpa, Kanker paru, Kanker rahim, Kanker uvula, Kanker, Kolera, Kolesistosis, Kolik, Kolitis, Kongesti, Konvulsi, Kram, Kudis (dioles), Kutu rambut (dioles), Kutu rambut, Mempermudah persalinan, Infeksi jamur, Mual (hamil muda), Mual, Mukosis, Neuralgia, Nyeri, Parasit, Pasokan susu yang buruk, Penyakit bronkus paru, Penyakit ginjal, Penyakit hati, Penyakit jamur, Penyakit lambung, Penyakit limpa, Penyakit pernafasan, Penyakit rongga mulut, Penyakit sendi, Penyakit tenggorokan, Psorias, Radang selaput lendir hidung dan tenggorokan, Sakit kepala sebelah, Sakit pinggang, Selesma, Sendawa/ Perut kembung, Sklerosis, Susah tidur, Terapi pengganti estrogen, Trakeosis, Tuber kulosis, Tumor, Ulkus (Borok), Virus.',
                'penggunaan_tradisional' => 'Adas manis (Pimpinella anisum) merupakan rempah-rempah dengan rasa manis pada bijinya, sangat baik untuk menghilangkan lendir di dalam tubuh, mengatasi kram perut, kolik dan perut kembung. Adas Manis sangat baik digunakan sebagai penenang sistim saraf dan mengatasi masalah sulit tidur. Adas manis merupakan bahan baku obat antivirus yang dapat menangani virus flu burung, ekstrak adas manis atau kembang lawang ini diekspor ke Korea yang selanjutnya dibuat antivirus flu burung yang bernama "Tamiflu". Adas manis digunakan sebagai rempah-rempah dalam memberikan rasa pada kari, permen, kue dan minuman. Daunnya juga digunakan dalam memberikan rasa pada berbagai permen. Buahnya dapat menghasilkan minyak atsiri yang dapat dipakai sebagai pengganti buahnya. Minyak adas manis dapat juga digunakan sebagai bahan untuk parfum, sabun dan insektisida. Buah adas manis juga digunakan sebagai tonik untuk ibu-ibu setelah melahirkan.',
                'dosis_harian' => '1 sendok teh biji dilembutkan/ cangkir air 3×/ hari, 3 g biji, atau 300 mg minyak biji/ hari 0,5 - 1 g biji sebagai minuman teh, 3×/ hari 0,5 - 3 g buah, 20 g buah dalam air, 0,5 - 1 sendok teh sirup hingga 3×/ hari, Minyak esensial 0,05 - 0,2 ml buah, 0,3 - 1 ml air adas manis. Atau, penggunaan internal: Dosis harian rata-rata 3 g. Minum 1 cangkir teh di pagi atau sore hari sebagai ekspektoran. 2 sendok makan untuk mengatasi keluhan lambung. Untuk bayi, dapat menggunakan seduhan 1 sendok teh yang ditambahkan pada botol minumannya. Penggunaan eksternal: Minyak esensialnya dapat digunakan dengan cara dihirup.',
                'kontra_indikasi' => 'Tidak ada bahaya Kesehatan atau efek samping yang dikenal dengan pemberian dosis terapi yang tepat. Dikontraindikasikan pada pasien alergi, namun sangat jarang terjadi. Reaksi alergi sesekali pada kulit, saluran pernapasan dan saluran pencernaan. Minyak esensial adas manis memiliki efek anti bakteri, antivirus, ekspektoran, estrogenik, karminatif, pengusir nyamuk dan spasmolitik ringan. 1 - 5 ml dapat menyebabkan mual, edema paru, kejang, dan muntah. Minyak Esensial LD50= 2.700 mg/ kg ORL tikus. Kontraindikasi untuk buah: hipersensitivitas. Efek samping: terkadang terdapat reaksi alergi. Biji, dilaporkan bersifat abortifasien dan laktagoga, sebaiknya tidak digunakan pada kehamilan. "Sering digunakan dalam praktek pediatrik". Ibu menyusui mengkonsumsi adas manis atau teh adas, atau keduanya, untuk merangsang laktasi. Dosis berlebihan dapat mengganggu antikoagulan, kontrasepsi, terapi pengganti estrogen, dan terapi penghambat Monoamin Oksidase (Monoamine Oxidase Inhibitor, MAOI). Adas manis berpotensi seperti efek estrogen.',
                'dapus' => '',
                'sumber_internet' => '',
                'gambar' => ''
            ],
            // Data KE 5
            [
                'nama_tumbuhan' => 'AKAR MANIS (LICORICE)',
                'nama_latin' => 'Glycyrrhiza glabra L.',
                'sinonim' => 'Anethum dulce DC.|Foeniculum giganteum Lojac.|Anethum foeniculum L.|Foeniculum officinale All.|Anethum minus Gouan|Foeniculum panmorium (Roxb.) DC.|Anethum panmori Roxb.|Foeniculum piperitum C. Presl|Anethum panmorium Roxb. ex Fleming|Foeniculum rigidum Brot. ex Steud.|Anethum pannorium Roxb.|Ligusticum foeniculum (L.) Crantz|Anethum rupestre Salisb.|Ligusticum foeniculum (L.) Roth|Foeniculum azoricum Mill.|Meum foeniculum (L.y) Spreng.|Foeniculum divaricatum Griseb.|Selinum foeniculum E. H. L. Krause|Foeniculum dulce Mill.|Seseli foeniculum Koso-Pol.',
                'nama_daerah' => 'Adas manis, jintan manis',
                'kerajaan' => 'Plantae (Tumbuhan)',
                'sub_kerajaan' => 'Tracheobionta (Tumbuhan berpembuluh)',
                'super_divisi' => 'Spermatophyta (Tumbuhan berbiji)',
                'divisi' => 'Magnoliophyta (Tumbuhan berbunga)',
                'kelas' => 'Magnoliopsida (Berkeping dua/ Dikotil)',
                'sub_kelas' => 'Rosidae',
                'ordo' => 'Apiales',
                'famili' => 'Apiaceae',
                'genus' => 'Pimpinella',
                'spesies' => 'Pimpinella anisum L.',
                'deskripsi' => 'Terna setahun, tinggi 10 - 45 cm. Batang beruas-ruas sempit. Daun menyirip ganda. Bunga memiliki mahkota yang mirip dengan kelopak. Buah berupa kapsul bulat, licin. Biji bersudut tiga, beriga melintang. Jintan manis merupakan jenis tumbuhan yang belum banyak dibudidayakan oleh masyarakat Indonesia.',
                'bagian_yg_digunakan' => 'Minyak esensial yang berasal dari buah yang matang dan buah yang kering.',
                'konstituen' => 'Minyak esensial: Alfa pinen, alfa-terpinen, anetol, anisaldehida, asam-anisat. Buah: Asetaldehida, asam-anisat, bergapten, dianetol, estragol. Daun: Alfa-tokoferol, imperatorin, isokuersitrin, skoparon, skopoletin, seselin. Tanaman: Alfa-zingiberen, anetol, beta-amirin, beta-bisabolen, asam-kafeat. Akar: Alfa-tokoferol, anetol, isopimpinelin, manitol. Biji: Anetol, dianetol, estragol, eugenol, umbeliferon. Minyak esensial biji: Beta-elemen, kamfor, karvon, sinamaldehida, sinamal-alkohol. Tunas: Anetol. Kultur jaringan: Alfa-tokoferol, anetol, beta-bisabolen, beta-sitosterol, miristisin.',
                'indikasi' => 'Andropause, Anemia, Anoreksia, Asma Bakteria, Batuk rejan (Pertusis), Batuk, Bau mulut, Demam, Nyeri haid, Dispepsia, Dropsi, Epilepsi, Frigiditas, Gugup, Indurasi, Infeksi, Kanker ginjal, Kanker hati, Kanker kandung kemih, Kanker lambung, Kanker limpa, Kanker paru, Kanker rahim, Kanker uvula, Kanker, Kolera, Kolesistosis, Kolik, Kolitis, Kongesti, Konvulsi, Kram, Kudis (dioles), Kutu rambut (dioles), Kutu rambut, Mempermudah persalinan, Infeksi jamur, Mual (hamil muda), Mual, Mukosis, Neuralgia, Nyeri, Parasit, Pasokan susu yang buruk, Penyakit bronkus paru, Penyakit ginjal, Penyakit hati, Penyakit jamur, Penyakit lambung, Penyakit limpa, Penyakit pernafasan, Penyakit rongga mulut, Penyakit sendi, Penyakit tenggorokan, Psorias, Radang selaput lendir hidung dan tenggorokan, Sakit kepala sebelah, Sakit pinggang, Selesma, Sendawa/ Perut kembung, Sklerosis, Susah tidur, Terapi pengganti estrogen, Trakeosis, Tuber kulosis, Tumor, Ulkus (Borok), Virus.',
                'penggunaan_tradisional' => 'Adas manis (Pimpinella anisum) merupakan rempah-rempah dengan rasa manis pada bijinya, sangat baik untuk menghilangkan lendir di dalam tubuh, mengatasi kram perut, kolik dan perut kembung. Adas Manis sangat baik digunakan sebagai penenang sistim saraf dan mengatasi masalah sulit tidur. Adas manis merupakan bahan baku obat antivirus yang dapat menangani virus flu burung, ekstrak adas manis atau kembang lawang ini diekspor ke Korea yang selanjutnya dibuat antivirus flu burung yang bernama "Tamiflu". Adas manis digunakan sebagai rempah-rempah dalam memberikan rasa pada kari, permen, kue dan minuman. Daunnya juga digunakan dalam memberikan rasa pada berbagai permen. Buahnya dapat menghasilkan minyak atsiri yang dapat dipakai sebagai pengganti buahnya. Minyak adas manis dapat juga digunakan sebagai bahan untuk parfum, sabun dan insektisida. Buah adas manis juga digunakan sebagai tonik untuk ibu-ibu setelah melahirkan.',
                'dosis_harian' => '1 sendok teh biji dilembutkan/ cangkir air 3×/ hari, 3 g biji, atau 300 mg minyak biji/ hari 0,5 - 1 g biji sebagai minuman teh, 3×/ hari 0,5 - 3 g buah, 20 g buah dalam air, 0,5 - 1 sendok teh sirup hingga 3×/ hari, Minyak esensial 0,05 - 0,2 ml buah, 0,3 - 1 ml air adas manis. Atau, penggunaan internal: Dosis harian rata-rata 3 g. Minum 1 cangkir teh di pagi atau sore hari sebagai ekspektoran. 2 sendok makan untuk mengatasi keluhan lambung. Untuk bayi, dapat menggunakan seduhan 1 sendok teh yang ditambahkan pada botol minumannya. Penggunaan eksternal: Minyak esensialnya dapat digunakan dengan cara dihirup.',
                'kontra_indikasi' => 'Tidak ada bahaya Kesehatan atau efek samping yang dikenal dengan pemberian dosis terapi yang tepat. Dikontraindikasikan pada pasien alergi, namun sangat jarang terjadi. Reaksi alergi sesekali pada kulit, saluran pernapasan dan saluran pencernaan. Minyak esensial adas manis memiliki efek anti bakteri, antivirus, ekspektoran, estrogenik, karminatif, pengusir nyamuk dan spasmolitik ringan. 1 - 5 ml dapat menyebabkan mual, edema paru, kejang, dan muntah. Minyak Esensial LD50= 2.700 mg/ kg ORL tikus. Kontraindikasi untuk buah: hipersensitivitas. Efek samping: terkadang terdapat reaksi alergi. Biji, dilaporkan bersifat abortifasien dan laktagoga, sebaiknya tidak digunakan pada kehamilan. "Sering digunakan dalam praktek pediatrik". Ibu menyusui mengkonsumsi adas manis atau teh adas, atau keduanya, untuk merangsang laktasi. Dosis berlebihan dapat mengganggu antikoagulan, kontrasepsi, terapi pengganti estrogen, dan terapi penghambat Monoamin Oksidase (Monoamine Oxidase Inhibitor, MAOI). Adas manis berpotensi seperti efek estrogen.',
                'dapus' => '',
                'sumber_internet' => '',
                'gambar' => ''
            ]
        ]);
    }
}
